const AdsActionTypes = {
  FILTER_ADS: 'FILTER_ADS',
  FILTER_ADS_BY_CATEGORY: 'FILTER_ADS_BY_CATEGORY',
  SET_ADS_FILTER: 'SET_ADS_FILTER',
  REMOVE_CATEGORY_FILTER: 'REMOVE_CATEGORY_FILTER',
  UPDATE_FILTERS_STATUS: 'UPDATE_FILTERS_STATUS',
  CLEAR_FILTERED_ADS: 'CLEAR_FILTERED_ADS',
  CLEAR_ALL_FILTERS: 'CLEAR_ALL_FILTERS',
  FETCH_ADS_SUCCESS: 'FETCH_ADS_SUCCESS',
};

export default AdsActionTypes;
