const AdsActionTypes = {
  FILTER_ADS: 'FILTER_ADS',
  FILTER_ADS_BY_CATEGORY: 'FILTER_ADS_BY_CATEGORY',
  SET_ADS_FILTER: 'SET_ADS_FILTER',
  REMOVE_CATEGORY_FILTER: 'REMOVE_CATEGORY_FILTER',
  NO_FILTER: 'NO_FILTER',
};

export default AdsActionTypes;
