const AdsActionTypes = {
  FILTER_ADS: 'FILTER_ADS',
  FILTER_ADS_BY_CATEGORY: 'FILTER_ADS_BY_CATEGORY',
  SET_ADS_FILTER: 'SET_ADS_FILTER',
  REMOVE_CATEGORY_FILTER: 'REMOVE_CATEGORY_FILTER',
  UPDATE_FILTER: 'UPDATE_FILTER',
  UPDATE_FILTERS_STATUS: 'UPDATE_FILTERS_STATUS',
  CLEAR_FILTERED_ADS: 'CLEAR_FILTERED_ADS',
  CLEAR_ALL_FILTERS: 'CLEAR_ALL_FILTERS',
  FETCH_ADS_START: 'FETCH_ADS_START',
  FETCH_TEN_LATEST_ADS_START: 'FETCH_TEN_LATEST_ADS_START',
  FETCH_ADS_SUCCESS: 'FETCH_ADS_SUCCESS',
  FETCH_ADS_FAILURE: 'FETCH_ADS_FAILURE',
  SORT_ADS_BY_DATE_ADDED: 'SORT_ADS_BY_DATE_ADDED',
  CREATE_AD_START: 'CREATE_AD_START',
  CREATE_AD_SUCCESS: 'CREATE_AD_SUCCESS',
  CREATE_AD_FAILURE: 'CREATE_AD_FAILURE',
};

export default AdsActionTypes;
